<a href="https://colab.research.google.com/github/xechehot/sirius-2021-warehouse/blob/main/Stefan/Test_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def my_split(x):
  ???

In [ ]:
my_split('a b c') == ['a', 'b', 'c']

In [ ]:
'апельсин мандарин ананас'.split('а')

['', 'пельсин м', 'нд', 'рин ', 'н', 'н', 'с']

In [ ]:
['a b c d']*3

['a b c d', 'a b c d', 'a b c d']

In [ ]:
data = [
        *['a b c d']*30,
        *['b c d']*40,
        *['c d']*50
]

In [ ]:
N = 5

In [ ]:
{
    'a': 17,
    'b': 14
}

{'a': 17, 'b': 14}

In [ ]:
# schedule (['a b c', 'a', 'b', 'a c'], 3)
['a b c', 'a', 'b', 'a c'] -> [['a b c'], ['a', 'b'], ['a c']]

In [ ]:
def schedule(lst, N):
  return [lst[i:i+N] for i in range(N)]

In [ ]:
ar = [1,2,3,4,5,6,7]

In [1]:
import numpy as np

In [5]:
block = np.zeros((5, 3), dtype=int)

In [7]:
block[3, 1] = 1

In [8]:
block

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 1, 0],
       [0, 0, 0]])

In [9]:
block[3, :]

array([0, 1, 0])

In [10]:
block[:, 1]

array([0, 0, 0, 1, 0])

In [13]:
block_list = [[0, 0, 0] for _ in range(5)]

In [20]:
block[3, :]+=[1,2,3]

In [21]:
block

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 3, 3],
       [0, 0, 0]])

In [32]:
np.random.choice()

array([0, 3])

In [37]:
ROWS = 12
SECTIONS = 17

In [44]:
def generate_positions(r, s, sz):
    rows = np.random.choice(r, sz)
    sections = np.random.choice(s, sz)
    return list(zip(rows, sections))

In [45]:
generate_positions(ROWS, SECTIONS, 2)

[(2, 0), (2, 8)]

In [52]:
NUM = 10
ones = generate_positions(ROWS, SECTIONS, 1)
distributed = generate_positions(ROWS, SECTIONS, NUM)
distributed_20 = generate_positions(ROWS, SECTIONS, NUM*2)
distributed_40 = generate_positions(ROWS, SECTIONS, NUM*4)
first_rows = generate_positions(np.arange(3), SECTIONS, NUM)
last_rows = generate_positions(np.arange(ROWS-3, ROWS), SECTIONS, NUM)
first_sections = generate_positions(ROWS, np.arange(3), NUM)
last_sections = generate_positions(ROWS, np.arange(SECTIONS-3, SECTIONS), NUM)

[(7, 12)]